# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: /dev/stdout
email: Pascal-0x90@protonmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hello world! I am Pascal. I will use this blog to share various thoughts,
  writeups, and other ideas which I feel like shooting out into the world.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://localhost:4000" # the base hostname & protocol for your site
twitter_username: pascal_0x90
github_username:  pascal-0x90
sass:
  sass_dir: _sass

include: [
  '_pages',
  ]

# Build settings
markdown: kramdown
kramdown:
  input: GFM
